{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Panic и recover"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Система типов Go позволяет найти многие ошибки во время компиляции, но некоторые ошибки как выход за границу массива или разыменовывание пустого указателя требуют проверки во время выполнения программы. Когда runtime языка Go находит такого рода ошибки, оно **паникует**(panic).\n",
    "\n",
    "Когда происходит паника, выполнение программы останавливается, выполняются все отложенные функции горутины, в которой произошла паника, и программа падает с выводом сообщения. Это сообщение содержит **значение паники**(panic value), которое обычно является сообщением об ошибке, и **трейс стека**(stack trace - стек вызовов функций) каждой активной во время паники горутины. Обычно этого сообщения бывает достаточно для определения причины паники.\n",
    "\n",
    "Не всегда паника исходит от runtime'а. Встроенная функция **panic** позволяет вызвать панику напрямую. На вход она принимает значение любого типа. Панику обычно вызывают в случаях, когда происходит что-то совсем \"невозможное\".\n",
    "\n",
    "Хотя механизм паник похож на механизм исключений из других языков программирования, ситуации, в которых вызывается паника, совершенно иные. Т.к. из-за паники программа завершает выполнение, паника в основном используются как посмертный лог, который подскажет разработчику причину падения. \"Нормальные\" ошибки, которые являются ожидаемыми программой, такие как неправильный ввод или настройка, ошибка при чтении данных из файла, невозможность сетевого подключения и т.д. не должны рассматриваться как исключения: программа должна уметь работать с такими ошибками.\n",
    "\n",
    "Как уже говорилось, после паники выполняются все отложенные функции горутины, в которой возникла паника:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import \"fmt\"\n",
    "\n",
    "func f(n int) {\n",
    "    fmt.Printf(\"f(%d)\\n\", n + 0/n) // Паника, когда n равно 0.\n",
    "    defer fmt.Printf(\"defer %d\\n\", n)\n",
    "    f(n - 1)\n",
    "}\n",
    "\n",
    "func main() {\n",
    "    f(3)\n",
    "}"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Также в Go возможно **восстановиться** после паники. Если встроенная функция **recover** вызывается в отложенной(deferred) функции и функция, содержащая отложенную функцию, паникует, то recover останавливает процесс паники и возвращает значение паники. Паникующая функция не выполняется дальше места, где произошла паника, а завершается нормально, т.е. с возвратом значения. Если recover вызвать в любой другой момент, то она просто возвращает nil и ничего особенного не происходит. Пример:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "panic message: STOP\n"
     ]
    }
   ],
   "source": [
    "import \"fmt\"\n",
    "\n",
    "func foo() (value int, err error) {\n",
    "    defer func() {\n",
    "        if p := recover(); p != nil {\n",
    "            err = fmt.Errorf(\"panic message: %v\", p)\n",
    "        }\n",
    "    }()\n",
    "    \n",
    "    panic(\"STOP\")\n",
    "}\n",
    "\n",
    "_, e := foo()\n",
    "fmt.Sprint(e)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Восстановление от паники можно использовать для выполнения какого-либо последнего действия перед завершением программы. Считается плохой практикой без явной необходимости восстанавливаться от паники, т.к. после паники значение переменных пакета редко бывает определённым. Восстановление от паники внутри пакета может быть хорошим способом обработки сложной ошибки, но в общем случае не нужно пытаться восстановиться от ошибки в другом пакете или функции, которую не контролируете. Публичное API должно возвращать ошибки в случае неудачи. Не от всех паник можно восстановиться: нехватка памяти вызовет завершение программы в любом случае с выводом сообщения."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Go (lgo)",
   "language": "go",
   "name": "lgo"
  },
  "language_info": {
   "file_extension": "",
   "mimetype": "",
   "name": "go",
   "version": ""
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
